### ISSUE TITLE
Dicionário de dados

### ISSUE THREAD

**Issue by omadson** [atlantico-academy/risk-prediction#4]
A equipe deve criar um arquivo (ou vários) de dicionário de dados, contendo informações referentes aos conjuntos de dados utilizados no projeto.

 - [x] Criar arquivo `data/external/dicionario.csv` contendo as seguintes colunas: `variavel`, `significado`, `tipo`.
 - [x] Inserir informações referentes ao arquivo de dados utilizado no projeto.

**Comment by marcelloale** [comment]
Começamos a criar o dicionario.csv
