### ISSUE TITLE
Exploração de dados

### ISSUE THREAD

**Issue by omadson** [atlantico-academy/risk-prediction#5]
A equipe deve criar um notebook de análise exploratória `notebooks/01-exploratory_data_analysis.ipynb`, contendo as seguintes seções de texto:

  - [x] **Descrição dos dados**: informações sobre a quantidade de instâncias, variáveis e seus tipos, quantidade de valores faltantes. Utilize o dicionário de dados nessa seção.
  - [x]  **Perguntas de partida e hipóteses**: que tipo de informações podem ser obtidas a partir dos dados e quais hipóteses podem ser levantadas?
  - [x]  **Insights**: respostas às perguntas feitas na seção anterior e quais informações interessantes podem ser levantadas através dos dados?

**Comment by gabriellfelix** [comment]
# Pendências:
- [ ] Tratar os Dados
- [x]  Descrever Insights
- [x] Mudar rótulos dos eixos dos gráficos
- [ ] Tornar as visualizações mais agradáveis
- [x] Trabalhar a resposta para a pergunta 8

**Comment by gabriellfelix** [comment]
# Perguntas
- Precisamos tratar os dados?
- Os insaghts precisam ser da relação entre o risco de inadiplência e as outras variáveis ou só entre as outras variáveis?
- O que significa o default da variável resposta de inadiplência?
- Descartamos os tipos dos dados que não estavam listados?

**Comment by omadson** [comment]
Respondendo as perguntas do @gabriellfelix 

> * Precisamos tratar os dados?

Não nessa etapa. Somente na etapa de preparação de dados.

> * Os insights precisam ser da relação entre o risco de inadiplência e as outras variáveis ou só entre as outras variáveis?

Qualquer variável que quiser, mas tentem focar nas relações entre a variável resposta e as outras.

> * O que significa o default da variável resposta de inadiplência?

Exatamente isso, inadimplência (https://www.lawinsider.com/dictionary/default-on-payment). **default payment** = inadimplência. É quando a pessoa deixa de pagar uma ou mais contas. O 1 aí no caso são pessoas que deixaram de pagar, o 0 são pessoas que pagaram tudo.

> * Descartamos os tipos dos dados que não estavam listados?

Como assim? Não entendi.

**Comment by marcelloale** [comment]
> > * Precisamos tratar os dados?
> 
> Não nessa etapa. Somente na etapa de preparação de dados.

Então as perguntas de partidas devem ser sobre como o estado do dataset? exemplo: Quantas linhas e conlunas, Tem dados duplicados, os dados estão balanceados?



> 
> > * Os insights precisam ser da relação entre o risco de inadiplência e as outras variáveis ou só entre as outras variáveis?
> 
> Qualquer variável que quiser, mas tentem focar nas relações entre a variável resposta e as outras.

Tentei fazer com o pandas-profiling mas ele nao mostrou opção de interação da def_pay com as demais variaveis, a variavel sex tambem não apareceu para fazer interação provavelmente por possuir apenas 2 valores. exemplo do que o profiling mostrou: Limit x age

> > * O que significa o default da variável resposta de inadiplência?
> 
> Exatamente isso, inadimplência (https://www.lawinsider.com/dictionary/default-on-payment). **default payment** = inadimplência. É quando a pessoa deixa de pagar uma ou mais contas. O 1 aí no caso são pessoas que deixaram de pagar, o 0 são pessoas que pagaram tudo.
> 

Isso foi um erro de tradução por ser um termo finaceiro, é até uma melhoria que possa ser acrescentada no dicionario, dada a confusão do binario representado na doc base como 1=yes 0=no mas o 0 é a pessoa que vai realizar o pagamento no proximo mês (Non Defaulters) e o 1 é para representar a pessoa que não vai realizar o pagamento no proximo mês (Defaulters)

> > * Descartamos os tipos dos dados que não estavam listados?
> 
> Como assim? Não entendi.

Fazendo a analise de dados percebemos que havia a falta informações na documentação original do data set em relação aos significados das variaveis, exemplo do Education: que possui variaveis 0,5,6 que não designado significado, tambem Marriage: 0 e PAY_0: -2 e 0. 
pensamos em seguir o padrão deste relato https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset/discussion/34608

**Comment by omadson** [comment]
> Então as perguntas de partidas devem ser sobre como o estado do dataset? exemplo: Quantas linhas e conlunas, Tem dados duplicados, os dados estão balanceados?

Sim, tem que ser sobre o estado do conjunto de dados, mas acho que agora entendi seu ponto. No caso de ter erros de semântica em relação aos dados, podem sim ser efetuadas transformações, mas não transformações das que passei na aula 02. Transformações do tipo, Na mesma coluna tem "No" e "no". Elas significam a mesma coisa, então podem escolher uma delas. Entende? 

> Tentei fazer com o pandas-profiling mas ele nao mostrou opção de interação da def_pay com as demais variaveis, a variavel sex tambem não apareceu para fazer interação provavelmente por possuir apenas 2 valores. exemplo do que o profiling mostrou: Limit x age

Não apareceu pq ele é automático e talvez só olhe variáveis contínuas. Você tem que criar gráficos usando o matplotlib e seaborn. Se quiser ideias de gráficos, dê uma olhada na galera do próprio seaborn: http://seaborn.pydata.org/examples/index.html

> Isso foi um erro de tradução por ser um termo finaceiro, é até uma melhoria que possa ser acrescentada no dicionario, dada a confusão do binario representado na doc base como 1=yes 0=no mas o 0 é a pessoa que vai realizar o pagamento no proximo mês (Non Defaulters) e o 1 é para representar a pessoa que não vai realizar o pagamento no proximo mês (Defaulters)

Ótimo.

> Fazendo a analise de dados percebemos que havia a falta informações na documentação original do data set em relação aos significados das variaveis, exemplo do Education: que possui variaveis 0,5,6 que não designado significado, tambem Marriage: 0 e PAY_0: -2 e 0. pensamos em seguir o padrão deste relato https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset/discussion/34608

Não necessáriamente precisam utilizar somente a página do conjunto de dados como fonte. É importante que busquem informação fora mesmo. Inclusive, não sei se viram, mas tem esse artigo (https://arxiv.org/pdf/1807.01176.pdf) que usa o conjunto de dados e fala sobre ele na seção IV.
