### ISSUE TITLE
Apresentação de resultados (análise exploratória)

### ISSUE THREAD

**Issue by omadson** [atlantico-academy/risk-prediction#6]
A equipe deve produzir uma apresentação de slides de no **máximo 10min** para ser apresentada ao professor e o restante da turma.

**Comment by maluwastaken** [comment]
Link para a apresentação da análise exploratória: https://docs.google.com/presentation/d/1RphbEH_UDUwZwAYD18f_k_EkOq39QiyfP4CI4UaGAHU/edit?usp=sharing

**Comment by maluwastaken** [comment]
Link para a apresentação da análise exploratória: https://docs.google.com/presentation/d/1RphbEH_UDUwZwAYD18f_k_EkOq39QiyfP4CI4UaGAHU/edit?usp=sharing

**Comment by omadson** [comment]
Finalizando!
